# fly.toml app configuration file generated for wordz on 2023-09-24T03:10:43+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wordz"
primary_region = "cdg"

[build]

[[mounts]]
  source = "wordz_data"
  destination = "/data"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
